export const postData = {
    columnData: [
        'ID',
        'Tên bài viết',
        'Nội dung bài viết',
        'Trạng thái',
    ],
    rowData: [
        {'ID': 'P01234', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01235', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01236', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01237', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01238', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01239', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01240', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01241', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        { 'ID': 'P01242', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng' },
        {'ID': 'P01243', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01244', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01245', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01246', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01247', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01248', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01249', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01250', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01251', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01252', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01253', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01254', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01255', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01256', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01257', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01258', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        {'ID': 'P01259', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Chưa sử dụng'},
        {'ID': 'P01260', 'NamePost': 'Chăm sóc sức khỏe hậu covid', 'OverviewPost': 'Hậu covid là một trong những ....', 'Status': 'Đang sử dụng'},
        
    ],
}