export const customerData = {
    columnData: [
        'ID',
        'Tên đối tác',
        'Tên người đánh giá',
        'Chức vụ',
        'Lời đánh giá',
    ],
    rowData: [
        {'ID': 'C01234', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01235', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01236', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01237', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01238', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01239', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01240', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01241', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01243', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01244', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01245', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01246', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01247', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01248', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01249', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01250', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01251', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01252', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01253', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01254', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01255', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01256', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01257', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01258', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01259', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01260', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01261', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01262', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01263', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01264', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01265', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01266', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01267', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01268', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01269', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01270', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01271', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01272', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01273', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01274', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01275', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01276', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01277', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01278', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01279', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01280', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01281', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01282', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01283', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01284', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01285', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01286', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01287', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01288', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01289', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01290', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01291', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01292', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01293', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01294', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01295', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01296', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01297', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01298', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01299', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
        {'ID': 'C01300', 'NameCustomer': 'Karaoke Icool', 'NameReviewer': 'Anh Sơn', 'Position': 'Quản lý', 'Review': 'Mình là quản lý Karaoke...'},
    ],
}