// import { dataUser } from './getDataUser'
export const userData = {
    columnData: [
        'ID',
        'Tên người dùng',
        'Email',
        'Mật khẩu',
    ],
    rowData: [
        {'ID': '3211', 'Username': 'Otto', 'Email': '@mdo', 'Password': '1234' },
        {'ID': '3212', 'Username': 'Thornton', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3213', 'Username': 'Bird', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3214', 'Username': 'Khánh', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3215', 'Username': 'Hảo', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3216', 'Username': 'Phương', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3217', 'Username': 'Nhật', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3218', 'Username': 'Cẩn', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3219', 'Username': 'Trình', 'Email': '@twitter', 'Password': '1234' },
        {'ID': '3220', 'Username': 'Otto', 'Email': '@mdo', 'Password': '1234' },
        {'ID': '3221', 'Username': 'Thornton', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3222', 'Username': 'Bird', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3223', 'Username': 'Khánh', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3224', 'Username': 'Hảo', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3225', 'Username': 'Phương', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3226', 'Username': 'Nhật', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3227', 'Username': 'Cẩn', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3228', 'Username': 'Trình', 'Email': '@twitter', 'Password': '1234' },
        {'ID': '3229', 'Username': 'Otto', 'Email': '@mdo', 'Password': '1234' },
        {'ID': '3230', 'Username': 'Thornton', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3231', 'Username': 'Bird', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3232', 'Username': 'Khánh', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3233', 'Username': 'Hảo', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3234', 'Username': 'Phương', 'Email': '@twitter', 'Password': '1234'},
        {'ID': '3235', 'Username': 'Nhật', 'Email': '@mdo', 'Password': '1234'},
        {'ID': '3236', 'Username': 'Cẩn', 'Email': '@fat', 'Password': '1234'},
        {'ID': '3237', 'Username': 'Trình', 'Email': '@twitter', 'Password': '1234'},
    ],
    // rowData: dataUser,
}