export const projectData = {
    columnData: [
        'ID',
        'Tên dự án',
        'Nội dung dự án',
        'Loại dự án',
    ],
    rowData: [
        {'ID': 'DA3211', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3212', 'ProjectName': 'Quản lý học sinh', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3213', 'ProjectName': 'Quản lý điểm rèn luyện sinh viên', 'ProjectContent': '@twitter', 'ProjectType': 'Mobile'},
        {'ID': 'DA3214', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3215', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3216', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3217', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'App'},
        {'ID': 'DA3218', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3219', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3220', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3221', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3222', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3223', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3224', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3225', 'ProjectName': 'Quản lý học sinh', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3226', 'ProjectName': 'Quản lý điểm rèn luyện sinh viên', 'ProjectContent': '@twitter', 'ProjectType': 'Mobile'},
        {'ID': 'DA3227', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3228', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3229', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3230', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'App'},
        {'ID': 'DA3231', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3232', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3233', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3234', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3235', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3236', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3237', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3238', 'ProjectName': 'Quản lý học sinh', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3239', 'ProjectName': 'Quản lý điểm rèn luyện sinh viên', 'ProjectContent': '@twitter', 'ProjectType': 'Mobile'},
        {'ID': 'DA3240', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3241', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3242', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3243', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'App'},
        {'ID': 'DA3244', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3245', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3246', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3247', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3248', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3249', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3250', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3251', 'ProjectName': 'Quản lý học sinh', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3252', 'ProjectName': 'Quản lý điểm rèn luyện sinh viên', 'ProjectContent': '@twitter', 'ProjectType': 'Mobile'},
        {'ID': 'DA3253', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'Web'},
        {'ID': 'DA3254', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'Mobile'},
        {'ID': 'DA3255', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3256', 'ProjectName': 'Quản lý Đoàn viên', 'ProjectContent': '@mdo', 'ProjectType': 'App'},
        {'ID': 'DA3257', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3258', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3259', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3260', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        {'ID': 'DA3261', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@fat', 'ProjectType': 'App'},
        {'ID': 'DA3262', 'ProjectName': 'Icool quản lý doanh số', 'ProjectContent': '@twitter', 'ProjectType': 'Game'},
        
    ],
}